if: tag IS blank # don't build tags
sudo: true # travis-ci/travis-ci#9033
os: linux
language: cpp
compiler: gcc
notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

matrix:
  include:
    # GCC 5
    - env: BUILD_TYPE=Debug
    - env: BUILD_TYPE=Release

    # Clang
    - compiler: clang
      env: BUILD_TYPE=Debug
    - compiler: clang
      env: BUILD_TYPE=Release

script:
  - cd test
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make -j
  - ctest --output-on-failure
